### PR TITLE
 90 create organization events page backend

### LINKED ISSUE #90: Create Organization Events Page + Backend
PREREQ: #78  -> if this is not done yet, just build the page and connect what you can

Use existing components to create the organization events page as shown in the Figma: 

DONT ADD POSTPONED EVENTS FOR NOW 

Screenshot 2024-05-01 at 7 19 50 PM

Connect all the fields to the backend: 
- when a user makes a request for an event from the calendar it shows up in the "pending", once the event is approved or denied it moves to the correct tables 
- when user deletes an event it actually removes from the database (or at least from the calendar and event bar)
- if an event time is in the past, it is in the past events table 
- also add a place for notes in declined events -> think about how we might want to store this in the backend

### PR DESCRIPTION
**Pull request by mtbosio**
…nt requests etc. Connected to backend

## Developer: Matthew Bosio

Closes #90 

### Pull Request Summary

- created Organizations Events page where users (orgs) can see outgoing event requests, approved, denied, and past events. Accessible at /organizationEvents. Connected database events to page. 

### Modifications
- OrganizationsEventsRequestTable.tsx : component for organizationEvents page. Added delete event functionality.
- eventSchema.ts : changed event schema to work with changes required. Added a deniedReason (if event is denied), a createdBy (when an event is created this must be filled in to be the ObjectId of the currently signed in org/user), and changed status to a string (naming convention: Approved, Denied, Pending). 
- api/users/eventRoutes.ts : changed the GET route to get events by createdBy ID instead of just getting all users. Also modified the DELETE route slightly so it'd work properly.
- organizationEvents.tsx : created to represent the page where users can see their outgoing events. Fetches the events from the database. If an event date is already past, it is automatically put in the Archived Events.

### Testing Considerations

- if an event is added, it is not the organization page is not automatically rerendered (i.e. you can't see the new event without refreshing the page). I think this makes sense because users wont be on the page when they add an event.

### Pull Request Checklist

- [ ] Code is neat, readable, and works
- [ ] Comments are appropriate
- [ ] The commit messages follows our [guidelines](https://h4i.notion.site/Conventional-Commits-593452ad1179489399ad3bd696ef772a)
- [ ] The developer name is specified
- [ ] The summary is completed
- [ ] Assign reviewers

### Screenshots/Screencast

https://www.loom.com/share/5acf0a8a30814e2380faf99091aeb07c?sid=a0cf8d88-dbee-44fb-90da-99732983dc88

### CODE REVIEW

**Review by ZealSV — APPROVED** [review]
Looks good!

**Review by ZealSV — APPROVED** [review]
Nice!

**Comment by mtbosio** [comment]
- Fixed merge conflicts. 
- Changed the schema:
    * removed time, no one was using it because time is embedded in the start and end dates
    * added deniedReason because I need it for if an event gets denied
- tested adding an event through the add event button, tested deleting an event from organizationEvents page, everything seems to work

**Review by ZealSV — APPROVED** [review]
Great work!

**Pull request merged**
